# Generated by Django 3.2.9 on 2021-11-07 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pessoas', '0002_pessoas_userid'),
        ('Alunos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunos',
            name='PessoaId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='AlunosPessoas', to='Pessoas.pessoas', verbose_name='Pessoa'),
        ),
    ]
