# Generated by Django 3.2.9 on 2021-11-15 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimentos',
            fields=[
                ('AlimentoId', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='AlimentoId')),
                ('Nome', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('Descricao', models.CharField(max_length=150, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Alimento',
                'db_table': 'Alimentos',
                'ordering': ('Nome',),
            },
        ),
        migrations.CreateModel(
            name='Itens',
            fields=[
                ('ItemId', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ItemId')),
                ('Nome', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('Descricao', models.CharField(max_length=150, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Item',
                'db_table': 'Itens',
                'ordering': ('Nome',),
            },
        ),
        migrations.CreateModel(
            name='Medicamentos',
            fields=[
                ('MedicamentoId', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='MedicamentoId')),
                ('Nome', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('Descricao', models.CharField(max_length=150, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Medicamento',
                'db_table': 'Medicamentos',
                'ordering': ('Nome',),
            },
        ),
        migrations.CreateModel(
            name='Pessoas',
            fields=[
                ('PessoaId', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='PessoaId')),
                ('Nome', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('Apelido', models.CharField(max_length=50, verbose_name='Apelido')),
                ('DataNascimento', models.DateField(null=True, verbose_name='Data de Nascimento')),
                ('CPF', models.DecimalField(decimal_places=0, max_digits=11, null=True, verbose_name='CPF')),
                ('RG', models.CharField(max_length=11, null=True, verbose_name='RG')),
                ('EMail', models.EmailField(max_length=254)),
                ('Senha', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Pessoa',
                'db_table': 'Pessoas',
                'ordering': ('Nome',),
            },
        ),
        migrations.CreateModel(
            name='Turmas',
            fields=[
                ('TurmaId', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='TurmaId')),
                ('Nome', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('AnoLetivo', models.IntegerField(verbose_name='Ano Letivo')),
                ('AnoEscolar', models.IntegerField(verbose_name='Ano Escolar')),
            ],
            options={
                'verbose_name': 'Turma',
                'db_table': 'Turmas',
                'ordering': ('AnoLetivo', 'AnoEscolar'),
            },
        ),
    ]
