# Generated by Django 3.2.9 on 2021-11-17 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import localflavor.br.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendas',
            fields=[
                ('Agenda_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Agenda_id')),
                ('Data', models.DateField()),
            ],
            options={
                'verbose_name': 'Agendas',
                'db_table': 'Agendas',
            },
        ),
        migrations.CreateModel(
            name='Alimentos',
            fields=[
                ('Alimento_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Alimento_id')),
                ('Nome', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('Descricao', models.CharField(max_length=150, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Alimento',
                'db_table': 'Alimentos',
                'ordering': ('Nome',),
            },
        ),
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('Aluno_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Aluno_id')),
            ],
            options={
                'verbose_name': 'Aluno',
                'db_table': 'Alunos',
            },
        ),
        migrations.CreateModel(
            name='Itens',
            fields=[
                ('Item_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Item_id')),
                ('Nome', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('Descricao', models.CharField(max_length=150, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Item',
                'db_table': 'Itens',
                'ordering': ('Nome',),
            },
        ),
        migrations.CreateModel(
            name='Medicamentos',
            fields=[
                ('Medicamento_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Medicamento_id')),
                ('Nome', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('Descricao', models.CharField(max_length=150, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Medicamento',
                'db_table': 'Medicamentos',
                'ordering': ('Nome',),
            },
        ),
        migrations.CreateModel(
            name='Pessoas',
            fields=[
                ('Pessoa_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Pessoa_id')),
                ('Nome', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('Apelido', models.CharField(max_length=50, verbose_name='Apelido')),
                ('DataNascimento', models.DateField(null=True, verbose_name='Data de Nascimento')),
                ('CPF', localflavor.br.models.BRCPFField(max_length=14, null=True, verbose_name='CPF')),
                ('RG', models.CharField(max_length=11, null=True, verbose_name='RG')),
                ('EMail', models.EmailField(max_length=254)),
                ('Senha', models.CharField(max_length=150)),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pessoa',
                'db_table': 'Pessoas',
                'ordering': ('Nome',),
            },
        ),
        migrations.CreateModel(
            name='Professores',
            fields=[
                ('Professor_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Professor_id')),
                ('Pessoa', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='Cadastros.pessoas')),
            ],
            options={
                'verbose_name': 'Professor',
                'db_table': 'Professores',
            },
        ),
        migrations.CreateModel(
            name='Responsaveis',
            fields=[
                ('Responsavel_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Responsavel_id')),
                ('Pessoa', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='Cadastros.pessoas')),
            ],
            options={
                'verbose_name': 'Responsavel',
                'db_table': 'Responsaveis',
            },
        ),
        migrations.CreateModel(
            name='Turmas',
            fields=[
                ('TurmaId', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='TurmaId')),
                ('Nome', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('AnoLetivo', models.IntegerField(verbose_name='Ano Letivo')),
                ('AnoEscolar', models.IntegerField(verbose_name='Ano Escolar')),
            ],
            options={
                'verbose_name': 'Turma',
                'db_table': 'Turmas',
                'ordering': ('AnoLetivo', 'AnoEscolar'),
            },
        ),
        migrations.CreateModel(
            name='TurmasProfessores',
            fields=[
                ('TurmaProfessor_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Matricula_id')),
                ('Professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cadastros.professores')),
                ('Turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cadastros.turmas')),
            ],
            options={
                'verbose_name': 'Professores por Turma',
                'db_table': 'TurmasProfessores',
            },
        ),
        migrations.CreateModel(
            name='ResponsaveisAlunos',
            fields=[
                ('ResponsavelAluno_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ResponsavelAluno_id')),
                ('Aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cadastros.alunos')),
                ('Responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cadastros.responsaveis')),
            ],
            options={
                'verbose_name': 'ResponsavelAluno',
                'db_table': 'ResponsaveisAlunos',
            },
        ),
        migrations.CreateModel(
            name='Prescricoes',
            fields=[
                ('Prescricao_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Matricula_id')),
                ('DataInicial', models.DateField()),
                ('DataFinal', models.DateField()),
                ('Posologia', models.TextField()),
                ('Horarios', models.TextField()),
                ('Alunos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cadastros.alunos')),
                ('Medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cadastros.medicamentos')),
            ],
            options={
                'verbose_name': 'Prescrições',
                'db_table': 'Prescricoes',
            },
        ),
        migrations.CreateModel(
            name='Matriculas',
            fields=[
                ('Matricula_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Matricula_id')),
                ('Aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cadastros.alunos')),
                ('Turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cadastros.turmas')),
            ],
            options={
                'verbose_name': 'Matrículas',
                'db_table': 'Matriculas',
            },
        ),
        migrations.AddField(
            model_name='alunos',
            name='Pessoa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='Cadastros.pessoas'),
        ),
        migrations.CreateModel(
            name='AgendasSonos',
            fields=[
                ('AgendaSono_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='AgendaSono_id')),
                ('DiaHoraRegistro', models.DateTimeField(auto_now_add=True)),
                ('Inicio', models.TimeField()),
                ('Fim', models.TimeField()),
                ('Agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cadastros.agendas')),
            ],
            options={
                'verbose_name': 'Sonos da Agenda',
                'db_table': 'AgendasSonos',
            },
        ),
        migrations.CreateModel(
            name='AgendasRecados',
            fields=[
                ('AgendaRecado_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='AgendaRecado_id')),
                ('DiaHoraRegistro', models.DateTimeField(auto_now_add=True)),
                ('Recado', models.TextField()),
                ('Agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cadastros.agendas')),
            ],
            options={
                'verbose_name': 'Recados da Agenda',
                'db_table': 'AgendasRecados',
            },
        ),
        migrations.CreateModel(
            name='AgendasMedicamentos',
            fields=[
                ('AgendaMedicamento_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='AgendaMedicamento_id')),
                ('DiaHoraRegistro', models.DateTimeField(auto_now_add=True)),
                ('Hora', models.TimeField()),
                ('PosologiaAdministrada', models.CharField(max_length=50)),
                ('Agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cadastros.agendas')),
                ('Prescricao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cadastros.prescricoes')),
            ],
            options={
                'verbose_name': 'Medicamentos da Agenda',
                'db_table': 'AgendasMedicamentos',
            },
        ),
        migrations.CreateModel(
            name='AgendasItens',
            fields=[
                ('AgendaAlimento_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='AgendaItem_id')),
                ('DiaHoraRegistro', models.DateTimeField(auto_now_add=True)),
                ('Agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cadastros.agendas')),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cadastros.itens')),
            ],
            options={
                'verbose_name': 'Itens da Agenda',
                'db_table': 'AgendasItens',
            },
        ),
        migrations.CreateModel(
            name='AgendasFisiologias',
            fields=[
                ('AgendaAlimento_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='AgendaFisiologia_id')),
                ('DiaHoraRegistro', models.DateTimeField(auto_now_add=True)),
                ('Fisiologia', models.CharField(choices=[('F', 'Fralda'), ('U', 'Urina'), ('Z', 'Fezes'), ('V', 'Vômito')], default='F', max_length=1)),
                ('Hora', models.TimeField()),
                ('Agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cadastros.agendas')),
            ],
            options={
                'verbose_name': 'Fisiologias da Agenda',
                'db_table': 'AgendasFisiologias',
            },
        ),
        migrations.CreateModel(
            name='AgendasBanhos',
            fields=[
                ('AgendaBanho_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='AgendaBanho_id')),
                ('DiaHoraRegistro', models.DateTimeField(auto_now_add=True)),
                ('Hora', models.TimeField()),
                ('Agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cadastros.agendas')),
            ],
            options={
                'verbose_name': 'Banhos da Agenda',
                'db_table': 'AgendasBanhos',
            },
        ),
        migrations.CreateModel(
            name='AgendasAlimentos',
            fields=[
                ('AgendaAlimento_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='AgendaAlimento_id')),
                ('DiaHoraRegistro', models.DateTimeField(auto_now_add=True)),
                ('Aceite', models.CharField(choices=[('O', 'Ótimo'), ('R', 'Regular'), ('G', 'Rejeitou')], default='R', max_length=1)),
                ('Hora', models.TimeField()),
                ('Agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cadastros.agendas')),
                ('Alimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cadastros.alimentos')),
            ],
            options={
                'verbose_name': 'Alimentos da Agenda',
                'db_table': 'AgendasAlimentos',
            },
        ),
        migrations.AddField(
            model_name='agendas',
            name='Matricula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cadastros.matriculas'),
        ),
        migrations.AddField(
            model_name='agendas',
            name='TurmaProfessor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cadastros.turmasprofessores'),
        ),
    ]
