# Generated by Django 3.2.9 on 2021-11-16 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimentos',
            fields=[
                ('Alimento_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Alimento_id')),
                ('Nome', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('Descricao', models.CharField(max_length=150, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Alimento',
                'db_table': 'Alimentos',
                'ordering': ('Nome',),
            },
        ),
        migrations.CreateModel(
            name='Itens',
            fields=[
                ('Item_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Item_id')),
                ('Nome', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('Descricao', models.CharField(max_length=150, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Item',
                'db_table': 'Itens',
                'ordering': ('Nome',),
            },
        ),
        migrations.CreateModel(
            name='Medicamentos',
            fields=[
                ('Medicamento_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Medicamento_id')),
                ('Nome', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('Descricao', models.CharField(max_length=150, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Medicamento',
                'db_table': 'Medicamentos',
                'ordering': ('Nome',),
            },
        ),
        migrations.CreateModel(
            name='Pessoas',
            fields=[
                ('Pessoa_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Pessoa_id')),
                ('Nome', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('Apelido', models.CharField(max_length=50, verbose_name='Apelido')),
                ('DataNascimento', models.DateField(null=True, verbose_name='Data de Nascimento')),
                ('CPF', models.DecimalField(decimal_places=0, max_digits=11, null=True, verbose_name='CPF')),
                ('RG', models.CharField(max_length=11, null=True, verbose_name='RG')),
                ('EMail', models.EmailField(max_length=254)),
                ('Senha', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Pessoa',
                'db_table': 'Pessoas',
                'ordering': ('Nome',),
            },
        ),
        migrations.CreateModel(
            name='Turmas',
            fields=[
                ('TurmaId', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='TurmaId')),
                ('Nome', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('AnoLetivo', models.IntegerField(verbose_name='Ano Letivo')),
                ('AnoEscolar', models.IntegerField(verbose_name='Ano Escolar')),
            ],
            options={
                'verbose_name': 'Turma',
                'db_table': 'Turmas',
                'ordering': ('AnoLetivo', 'AnoEscolar'),
            },
        ),
        migrations.CreateModel(
            name='Professores',
            fields=[
                ('Professor_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Professor_id')),
                ('Pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cadastros.pessoas')),
            ],
            options={
                'verbose_name': 'Professor',
                'db_table': 'Professores',
            },
        ),
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('Aluno_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Aluno_id')),
                ('Pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cadastros.pessoas')),
            ],
            options={
                'verbose_name': 'Aluno',
                'db_table': 'Alunos',
            },
        ),
    ]
