# Generated by Django 3.2.9 on 2021-11-17 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoas',
            name='Telefone',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='Apelido',
            field=models.CharField(max_length=50, null=True, verbose_name='Apelido'),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='Nome',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='Usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
