# Generated by Django 3.2.9 on 2021-11-16 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professores',
            name='Pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cadastros.pessoas', unique=True),
        ),
    ]
