# Generated by Django 3.2.9 on 2021-11-16 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastros', '0002_alter_professores_pessoa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunos',
            name='Pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cadastros.pessoas', unique=True),
        ),
    ]
