# Generated by Django 3.2.9 on 2021-11-17 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastros', '0002_auto_20211117_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoas',
            name='EMail',
        ),
        migrations.RemoveField(
            model_name='pessoas',
            name='Senha',
        ),
    ]
