# Generated by Django 3.2.9 on 2021-11-21 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastros', '0003_auto_20211117_1959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescricoes',
            old_name='Alunos',
            new_name='Aluno',
        ),
    ]
