# Generated by Django 3.2.9 on 2021-11-16 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastros', '0004_auto_20211116_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsaveis',
            fields=[
                ('Responsavel_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Responsavel_id')),
                ('Pessoa', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='Cadastros.pessoas')),
            ],
            options={
                'verbose_name': 'Responsavel',
                'db_table': 'Responsaveis',
            },
        ),
    ]
