# Generated by Django 3.2.9 on 2021-11-16 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastros', '0005_responsaveis'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsaveisAlunos',
            fields=[
                ('ResponsavelAluno_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ResponsavelAluno_id')),
                ('Aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cadastros.alunos')),
                ('Responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cadastros.responsaveis')),
            ],
            options={
                'verbose_name': 'ResponsavelAluno',
                'db_table': 'ResponsaveisAlunos',
            },
        ),
    ]
