# Generated by Django 3.2.9 on 2022-06-13 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastros', '0005_alter_pessoas_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabelasPrecos',
            fields=[
                ('TabelaPrecoId', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='TabelaPrecosId')),
                ('Nome', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('Valor', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor')),
            ],
            options={
                'verbose_name': 'Tabela',
                'verbose_name_plural': 'Tabelas',
                'db_table': 'TabelasPrecos',
                'ordering': ('Nome',),
            },
        ),
        migrations.AlterModelOptions(
            name='agendas',
            options={'verbose_name': 'Agenda', 'verbose_name_plural': 'Agendas'},
        ),
        migrations.AlterModelOptions(
            name='agendasalimentos',
            options={'verbose_name': 'Alimento da Agenda', 'verbose_name_plural': 'Alimentos das Agendas'},
        ),
        migrations.AlterModelOptions(
            name='agendasbanhos',
            options={'verbose_name': 'Banho da Agenda', 'verbose_name_plural': 'Banhos da Agenda'},
        ),
        migrations.AlterModelOptions(
            name='agendasfisiologias',
            options={'verbose_name': 'Fisiologia da Agenda', 'verbose_name_plural': 'Fisiologias da Agenda'},
        ),
        migrations.AlterModelOptions(
            name='agendasitens',
            options={'verbose_name': 'Item da Agenda', 'verbose_name_plural': 'Itens das Agendas'},
        ),
        migrations.AlterModelOptions(
            name='agendasmedicamentos',
            options={'verbose_name': 'Medicamento da Agenda', 'verbose_name_plural': 'Medicamentos das Agendas'},
        ),
        migrations.AlterModelOptions(
            name='agendasrecados',
            options={'verbose_name': 'Recado da Agenda', 'verbose_name_plural': 'Recados das Agendas'},
        ),
        migrations.AlterModelOptions(
            name='agendassonos',
            options={'verbose_name': 'Sono da Agenda', 'verbose_name_plural': 'Sonos das Agendas'},
        ),
        migrations.AlterModelOptions(
            name='alimentos',
            options={'ordering': ('Nome',), 'verbose_name': 'Alimento', 'verbose_name_plural': 'Alimentos'},
        ),
        migrations.AlterModelOptions(
            name='alunos',
            options={'verbose_name': 'Aluno', 'verbose_name_plural': 'Alunos'},
        ),
        migrations.AlterModelOptions(
            name='itens',
            options={'ordering': ('Nome',), 'verbose_name': 'Item', 'verbose_name_plural': 'Itens'},
        ),
        migrations.AlterModelOptions(
            name='matriculas',
            options={'verbose_name': 'Matrícula', 'verbose_name_plural': 'Matrículas'},
        ),
        migrations.AlterModelOptions(
            name='medicamentos',
            options={'ordering': ('Nome',), 'verbose_name': 'Medicamento', 'verbose_name_plural': 'Medicamentos'},
        ),
        migrations.AlterModelOptions(
            name='pessoas',
            options={'ordering': ('Nome',), 'verbose_name': 'Pessoa', 'verbose_name_plural': 'Pessoas'},
        ),
        migrations.AlterModelOptions(
            name='prescricoes',
            options={'verbose_name': 'Prescrição', 'verbose_name_plural': 'Prescrições'},
        ),
        migrations.AlterModelOptions(
            name='professores',
            options={'verbose_name': 'Professor', 'verbose_name_plural': 'Professores'},
        ),
        migrations.AlterModelOptions(
            name='responsaveis',
            options={'verbose_name': 'Responsavel', 'verbose_name_plural': 'Responsáveis'},
        ),
        migrations.AlterModelOptions(
            name='responsaveisalunos',
            options={'verbose_name': 'Responsavel pelo Aluno', 'verbose_name_plural': 'Responsáveis pelos Alunos'},
        ),
        migrations.AlterModelOptions(
            name='turmas',
            options={'ordering': ('AnoLetivo', 'AnoEscolar'), 'verbose_name': 'Turma', 'verbose_name_plural': 'Turmas'},
        ),
        migrations.AlterModelOptions(
            name='turmasprofessores',
            options={'verbose_name': 'Professor da Turma', 'verbose_name_plural': 'Professores das Turmas'},
        ),
        migrations.AlterField(
            model_name='agendas',
            name='Data',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='Telefone',
            field=models.CharField(max_length=16, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='prescricoes',
            name='DataFinal',
            field=models.DateField(verbose_name='Data final'),
        ),
        migrations.AlterField(
            model_name='prescricoes',
            name='DataInicial',
            field=models.DateField(verbose_name='Data inicial'),
        ),
        migrations.AlterField(
            model_name='prescricoes',
            name='Horarios',
            field=models.TextField(verbose_name='Horário'),
        ),
        migrations.AlterField(
            model_name='prescricoes',
            name='Posologia',
            field=models.TextField(verbose_name='Posologia'),
        ),
    ]
