# Generated by Django 3.2.9 on 2021-11-16 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastros', '0007_matriculas_turmasprofessores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescricoes',
            fields=[
                ('Prescricao_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Matricula_id')),
                ('DataInicial', models.DateField()),
                ('DataFinal', models.DateField()),
                ('Posologia', models.TextField()),
                ('Horarios', models.TextField()),
                ('Alunos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cadastros.alunos')),
                ('Medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cadastros.medicamentos')),
            ],
            options={
                'verbose_name': 'Prescrições',
                'db_table': 'Prescricoes',
            },
        ),
    ]
