# Generated by Django 3.2.9 on 2022-06-14 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastros', '0007_turmastabelas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsaveisMensalidades',
            fields=[
                ('ResponsavelMensalidade_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ResponsavelMensalidade_id')),
                ('Matricula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cadastros.matriculas')),
                ('Responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cadastros.responsaveisalunos')),
            ],
            options={
                'verbose_name': 'Compromisso financeiro do responsável',
                'verbose_name_plural': 'Compromissos financeiros do responsável',
                'db_table': 'ResponsaveisMensalidades',
            },
        ),
    ]
