# Generated by Django 3.2.9 on 2021-11-17 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastros', '0008_prescricoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendas',
            fields=[
                ('Agenda_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Agenda_id')),
                ('Data', models.DateField()),
                ('Matricula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cadastros.matriculas')),
                ('TurmaProfessor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cadastros.turmasprofessores')),
            ],
            options={
                'verbose_name': 'Agendas',
                'db_table': 'Agendas',
            },
        ),
    ]
