# Generated by Django 3.2.9 on 2022-06-15 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastros', '0008_responsaveismensalidades'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responsaveismensalidades',
            old_name='Responsavel',
            new_name='ResponsavelAluno',
        ),
    ]
