# Generated by Django 3.2.9 on 2022-06-15 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cadastros', '0009_rename_responsavel_responsaveismensalidades_responsavelaluno'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitulosBancarios',
            fields=[
                ('TituloBancario_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='TituloBancario_id')),
                ('Vencimento', models.DateField(db_index=True)),
                ('Valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Pagamento', models.DateField(blank=True, db_index=True, null=True)),
                ('NumeroBancario', models.CharField(blank=True, max_length=20, null=True)),
                ('Matricula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cadastros.matriculas')),
                ('ResponsavelMensalidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Cadastros.responsaveismensalidades')),
            ],
            options={
                'verbose_name': 'Mensalidade',
                'verbose_name_plural': 'Mensalidades',
                'db_table': 'TitulosBancarios',
            },
        ),
    ]
