# Generated by Django 3.2.9 on 2021-11-07 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Pessoas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoas',
            name='UserId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PessoasUsers', to=settings.AUTH_USER_MODEL),
        ),
    ]
