# Generated by Django 3.2.9 on 2021-11-06 23:25

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Pessoas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsaveis',
            fields=[
                ('ResponsavelId', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ResponsavelId')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='ResponsavelId', unique=True)),
                ('PessoaId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Pessoas', to='Pessoas.pessoas')),
            ],
            options={
                'verbose_name': 'Responsavel',
                'verbose_name_plural': 'Responsaveis',
                'db_table': 'responsaveis',
            },
        ),
    ]
