# Generated by Django 3.2.9 on 2021-11-08 01:29

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Agendas', '0001_initial'),
        ('Prescricoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendasMedicamentos',
            fields=[
                ('AgendaMedicamentoId', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='AgendaMedicamentoId')),
                ('DataHora', models.DateTimeField(auto_now_add=True, verbose_name='DataHora')),
                ('Hora', models.TimeField(verbose_name='Hora')),
                ('PosologiaAdministrada', models.CharField(max_length=50)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='AgendaMedicamentoId', unique=True)),
                ('AgendaId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='AgendasMedicamentosAgendas', to='Agendas.agendas', verbose_name='Agenda')),
                ('PrescricaoId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='AgendasMedicamentosPrescricoes', to='Prescricoes.prescricoes', verbose_name='Medicamento')),
            ],
            options={
                'verbose_name': 'AgendaMedicamento',
                'verbose_name_plural': 'AgendasAMedicamentos',
                'db_table': 'AgendasMedicamentos',
                'unique_together': {('AgendaId', 'PrescricaoId', 'Hora')},
            },
        ),
    ]
