# Generated by Django 3.2.9 on 2021-11-08 01:29

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Agendas', '0001_initial'),
        ('Alimentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendasAlimentos',
            fields=[
                ('AgendaAlimentoId', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='AgendaAlimentoId')),
                ('DataHora', models.DateTimeField(auto_now_add=True, verbose_name='DataHora')),
                ('Hora', models.TimeField(verbose_name='Hora')),
                ('Aceite', models.CharField(choices=[('O', 'Ótimo'), ('R', 'Regular'), ('G', 'Rejeitou')], max_length=1)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='AgendaAlimentoId', unique=True)),
                ('AgendaId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='AgendasAlimentosAgendas', to='Agendas.agendas', verbose_name='Agenda')),
                ('AlimentoId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='AgendasAlimentosAlimentos', to='Alimentos.alimentos', verbose_name='Alimento')),
            ],
            options={
                'verbose_name': 'AgendaAlimento',
                'verbose_name_plural': 'AgendasAlimentos',
                'db_table': 'AgendasAlimentos',
                'unique_together': {('AgendaId', 'AlimentoId', 'Hora')},
            },
        ),
    ]
