# Generated by Django 3.2.9 on 2021-11-07 14:05

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Alunos', '0002_alter_alunos_pessoaid'),
        ('Medicamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescricoes',
            fields=[
                ('PrescricaoId', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='PrescricaoId')),
                ('DataInicio', models.DateField(verbose_name='Data de Início')),
                ('DataFim', models.DateField(verbose_name='Data Final')),
                ('Posologia', models.CharField(max_length=50, verbose_name='Posologia')),
                ('Horarios', models.CharField(max_length=50, verbose_name='Horários')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='Prescricao', unique=True)),
                ('AlunoId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PrescricoesAluno', to='Alunos.alunos', verbose_name='Aluno')),
                ('MedicamentoId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PrescricoesMedicamento', to='Medicamentos.medicamentos', verbose_name='Medicamento')),
            ],
            options={
                'verbose_name': 'Prescricao',
                'verbose_name_plural': 'Prescricoes',
                'db_table': 'Prescricoes',
            },
        ),
    ]
