# Generated by Django 3.2.9 on 2021-11-07 01:32

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Pessoas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professores',
            fields=[
                ('ProfessorId', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ProfessorId')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='ProfessorId', unique=True)),
                ('PessoaId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ProfessoresPessoas', to='Pessoas.pessoas', verbose_name='Pessoa')),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
                'db_table': 'professores',
            },
        ),
    ]
