# Generated by Django 3.2.9 on 2021-11-08 01:29

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Agendas', '0001_initial'),
        ('Itens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendasItens',
            fields=[
                ('AgendaItemId', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='AgendaItemId')),
                ('DataHora', models.DateTimeField(auto_now_add=True, verbose_name='DataHora')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='AgendaItemId', unique=True)),
                ('AgendaId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='AgendasItensAgendas', to='Agendas.agendas', verbose_name='Agenda')),
                ('ItemId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='AgendasItensItens', to='Itens.itens', verbose_name='Item')),
            ],
            options={
                'verbose_name': 'AgendaItem',
                'verbose_name_plural': 'AgendasAItens',
                'db_table': 'AgendasItens',
                'unique_together': {('AgendaId', 'ItemId')},
            },
        ),
    ]
