# Generated by Django 3.2.9 on 2021-11-07 13:46

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Professores', '0001_initial'),
        ('Turmas', '0002_alter_turmas_anoescolar'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurmasProfessores',
            fields=[
                ('TurmaProfessorId', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='TurmaProfessorId')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='TurmaProfessor', unique=True)),
                ('ProfessorId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TurmasProfessoresProfessor', to='Professores.professores', verbose_name='Professor')),
                ('TurmaId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TurmasProfessoresTurma', to='Turmas.turmas', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'TurmaProfessor',
                'verbose_name_plural': 'TurmasProfessores',
                'db_table': 'TurmasProfessores',
            },
        ),
    ]
