# Generated by Django 3.2.9 on 2021-11-08 01:29

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Agendas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendasBanhos',
            fields=[
                ('AgendaBanhoId', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='AgendaBanhoId')),
                ('DataHora', models.DateTimeField(auto_now_add=True, verbose_name='DataHora')),
                ('Hora', models.TimeField()),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='AgendaBanhoId', unique=True)),
                ('AgendaId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='AgendasBanhosAgendas', to='Agendas.agendas', verbose_name='Agenda')),
            ],
            options={
                'verbose_name': 'AgendaBanho',
                'verbose_name_plural': 'AgendasABanhos',
                'db_table': 'AgendasBanhos',
            },
        ),
    ]
