# Generated by Django 3.2.9 on 2021-11-08 01:29

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Agendas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendasRecados',
            fields=[
                ('AgendaRecadoId', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='AgendaRecadoId')),
                ('DataHora', models.DateTimeField(auto_now_add=True, verbose_name='DataHora')),
                ('Recado', models.TextField()),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='AgendaRecadoId', unique=True)),
                ('AgendaId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='AgendasRecadosAgendas', to='Agendas.agendas', verbose_name='Agenda')),
            ],
            options={
                'verbose_name': 'AgendaRecado',
                'verbose_name_plural': 'AgendasARecados',
                'db_table': 'AgendasRecados',
            },
        ),
    ]
