# Generated by Django 3.2.9 on 2021-11-07 13:46

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Responsaveis', '0002_alter_responsaveis_pessoaid'),
        ('Alunos', '0002_alter_alunos_pessoaid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matriculas',
            fields=[
                ('MatriculaId', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='MatriculaId')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='Matricula', unique=True)),
                ('AlunoId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='MatriculasAluno', to='Alunos.alunos', verbose_name='Aluno')),
                ('TurmaId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='MatriculasTurma', to='Responsaveis.responsaveis', verbose_name='Turma')),
            ],
            options={
                'verbose_name': 'Matricula',
                'verbose_name_plural': 'Matriculas',
                'db_table': 'Matriculas',
            },
        ),
    ]
