# Generated by Django 3.2.9 on 2021-11-07 14:38

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Turmas', '0002_alter_turmas_anoescolar'),
        ('Alunos', '0002_alter_alunos_pessoaid'),
        ('Matriculas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matriculas',
            name='TurmaId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='MatriculasTurma', to='Turmas.turmas', verbose_name='Turma'),
        ),
        migrations.AlterField(
            model_name='matriculas',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='MatriculaId', unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='matriculas',
            unique_together={('TurmaId', 'AlunoId')},
        ),
    ]
