# Generated by Django 3.2.9 on 2021-11-06 22:07

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turmas',
            fields=[
                ('TurmaId', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='TurmaId')),
                ('AnoLetivo', models.IntegerField(verbose_name='Ano Letivo')),
                ('AnoEscolar', models.IntegerField(verbose_name='Ano Escola')),
                ('NomeTurma', models.CharField(max_length=50, verbose_name='Nome Da Turma')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='AnoLetivo', unique=True)),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'db_table': 'turmas',
                'ordering': ('AnoLetivo',),
            },
        ),
    ]
