# Generated by Django 3.2.9 on 2021-11-08 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Turmas', '0002_alter_turmas_anoescolar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turmas',
            old_name='NomeTurma',
            new_name='Nome',
        ),
    ]
